config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from ecom import views
from django.conf.urls import url, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/', include('ecom.urls')),
    path('ecom/payf.html', include('payments.urls')),
    url('', include('pwa.urls')),
    path('ecom/', include('django.contrib.auth.urls')), 
]

ecom/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls import url
from . import views as ecom_views
from django.views.generic.base import TemplateView # new

urlpatterns = [
    #path('',views.login, name="login"),
    path('', views.index, name="index"),
    path('index', views.index, name="index"),
    #path('login',views.login, name="login"),
    path('product.html', views.product, name="product"),
    path('', include('django.contrib.auth.urls')),
    path('signup', ecom_views.signup, name='signup'),
    path('signup1.html', ecom_views.signup, name='signup1'),
    path('pay.html', views.pay, name="pay"),
    path('history.html', views.history, name="history"),
    path('cancel/<product>', views.cancel, name='cancel')
    #path('pay1.html', TemplateView.as_view(template_name='pay1.html'), name='pay1'),
]

ecom/models.py
from django.db import models
from django.conf import settings
import uuid
from django.contrib.auth import login
from django.utils import timezone


#アカウント情報
class Person(models.Model):
    """Model representing unique user."""
    name = models.TextField()
    #username=request.user.username
    e_mail = models.EmailField()
    password = models.TextField()
    in_cart = models.IntegerField(default=0)
    #cart = models.OneToOneField(Cart,on_delete=models.CASCADE,primary_key=True,)
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular user')
    def __str__(self):
        """String for representing the Model object."""
        return self.name




#商品情報
class Item(models.Model):
    product = models.CharField(max_length=100)
    #pers = models.ManyToManyField(Person)
    picture = models.URLField()
    price = models.IntegerField(default=0)
    description = models.TextField()
    in_cart = models.IntegerField(default=0)
    def __str__(self):
        """String for representing the Model object."""
        return self.product



#購入履歴
class History(models.Model):
    name = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)
    item = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now)


#カートの中身
#class Cart(models.Model):
 #   owner = models.ForeignKey(Person, on_delete=models.SET_NULL,blank=True, null=True)
  #  money = models.IntegerField(default=0)

   # def __str__(self):
       # String for representing the Model object.
      # if request.user.is_authenticated:
    #        return self.name
class Cart(models.Model):
    person = models.CharField(max_length=100, default="prakhar")
    money = models.IntegerField(default=0)
    #item=models.ForeignKey(Item,on_delete=models.SET_NULL, null=True)

    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular user')

    def __str__(self):
       # String for representing the Model object.
      # if request.user.is_authenticated:
            return self.person

ecom/forms.py
from django import forms

class Product_form(forms.Form):
    CHOICE = (
    ('0', '数量を選択'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    )
    number = forms.ChoiceField(label="本数",widget=forms.Select, choices=CHOICE)

# class Login_form(forms.Form):
#     name = forms.CharField(label="name")
#     #e_mail = forms.EmailField(label="e_mail")
#     password = forms.CharField(label="password")

ecom/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.http import HttpResponse

from .models import Person, Item, History, Cart
from .forms import Product_form

from django.db.models import Q
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


import stripe
from ecom.models import *
from django.conf import settings
import stripe

# Create your views here.

from django.views.generic.base import TemplateView

from .models import History

import json

stripe.api_key = settings.STRIPE_SECRET_KEY

def index(request):
    products = Item.objects.all()
    params = {
        'products':products,
    }
    if request.user.is_authenticated:

        return render(request, 'ecom/index1.html', params)
    else:
        pay.items_in_cart=0
        return render(request, 'ecom/indexlo.html', params)




"""def login(request):
    params = {
        'login':Login_form
    }

    if request.method == "POST":
        authentication(request)
    return render(request, 'ecom/login.html', params)

def authentication(request):
    form = Login_form(data=request.POST)
    if form.is_valid():
        return redirect('views.index')
    form.add_error(None, '入力内容が違います。')
"""
def product(request):

   if (request.user.is_authenticated):
        cart = get_cart(request)
        number = 0
        buy_num = 0
        product_name = request.GET.get('product')
        product = Item.objects.get(product=product_name)
        cart.item = product
        print("check")

        if request.method == 'POST':
            print("check2")
            num = request.POST['number']
            buy_num = request.POST['number']
            product.in_cart = num
            cart = get_cart(request)
            tot=int(product.in_cart)*int(product.price)
            cart.money=cart.money+tot
            cart.save()
            item_in_cart = Item.objects.exclude(in_cart=0)
            #total_price=0
            #for item in item_in_cart:
            #   total_price = item.in_cart * item.price
            #  cart.money += total_price
            # cart.save()
            product.save()

        params = {
            'product':product,
            'form':Product_form(),
            # 'number':num,
            'cart':cart,
            'buy_num':buy_num,
            }


        return render(request, 'ecom/product.html', params)
   else:
      # messages.add_message(request, messages.INFO, 'login to proceed')
       return render(request, 'ecom/pay1.html')

def pay(request):
    if request.user.is_authenticated:
        username = request.user.username
        person = Person.objects.get(name=username)
        cart = get_cart(request)
        #item_in_cart = Item.objects.exclude(in_cart=0)
        item_in_cart = Item.objects.exclude(in_cart=0)
        #total_price = 0
        #for item in item_in_cart:
         #   total_price += item.in_cart * item.price
        #cart.money = total_price
        #cart.save()


        params = {
            'items':item_in_cart,
            'cart':cart,
        }

        '''if (request.method == 'POST' ):

            tmp = {}
            for item in item_in_cart:
                tmp[item.product] = item.in_cart
                item.in_cart = 0
                item.save()
                #cart.item.in_cart=0
                #cart.item={}


            cart.money = 0
            cart.save()
            history = History()
            person=Person.objects.get(name=request.user.username)
            history.name=person
            history.item = tmp

            #for history in History:
            history.save()

           # messages.success(request, '決済完了')
            return redirect(to='/ecom/pay.html')
            '''
        return render(request, 'ecom/pay.html',params)
    else:
            #messages.add_message(request, messages.INFO, 'Please login to buy form us.')
        return render(request, 'ecom/pay1.html')

def cancel(request, product):
    if request.user.is_authenticated:
        username = request.user.username
        person = Person.objects.get(name=username)
        cart = get_cart(request)
        #item_in_cart = Item.objects.exclude(in_cart=0)
        item = Item.objects.get(product=product)
        item.in_cart = 0
        item.save()
        return redirect('pay')

#----------------

def get_cart(request):
    #username = None
    if request.user.is_authenticated:
        username = request.user.username
        cart = Cart.objects.get_or_create(person=username)
        print(cart)
        #cart = Cart(request,00)

        return cart[0]

def history(request):
    person = Person.objects.get(name=request.user)
    data = History.objects.filter(name=person)

    params = {
        'data':data,
    }
    return render(request, 'ecom/history.html', params)



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            print('ok')
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)

            person=Person.objects.create(name=username,password=raw_password,e_mail="abc@ddd.com")
            person.save()
            cart=Cart.objects.create(person=username)
            cart.save()
            #username = request.username['username']
            #password = request.raw_password['password1']
            #user = authenticate(username=username, password=raw_password)
           # p=Person.objects.first()
           # p.save(force_insert=True)
            #model.Person.username= (username=username, password=raw_password)
            login(request, user)

            return redirect('index')
        else:
            return render(request,'signup1.html',{'form': form})
            print('fail')
    else:
        form = UserCreationForm()
    
        return render(request, 'signup.html', {'form': form})

ecom/templates/ecom/base.html
{% load static %}
{% load pwa %}
<!doctype html>

<head>
    {% progressive_web_app_meta %}
    <link rel="stylesheet" href="{% static 'ecom/css/normalize.css' %}">
    <link rel="stylesheet" type ="text/css"
          href="{% static 'ecom/css/style.css' %}" />
    <link rel="shortcut icon" href="../static/ecom/img/ecom_img.ico" type="image/x-icon">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>
 <body class="pay-body">
    <header background-color:#e6e6fa>
     <svg viewbox="0 0 100 20">
   	<defs>
    <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
      <stop offset="5%" stop-color="#326384"/>
      <stop offset="95%" stop-color="#123752"/>
    </linearGradient>
    <pattern id="wave" x="0" y="0" width="120" height="20" patternUnits="userSpaceOnUse">
      <path id="wavePath" d="M-40 9 Q-30 7 -20 9 T0 9 T20 9 T40 9 T60 9 T80 9 T100 9 T120 9 V20 H-40z" mask="url(#mask)" fill="url(#gradient)">
        <animateTransform
            attributeName="transform"
            begin="0s"
            dur="1.5s"
            type="translate"
            from="0,0"
            to="40,0"
            repeatCount="indefinite" />
      </path>
    </pattern>
   </defs>
   <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#wave)"  fill-opacity="0.6">DeM-iON</text>
   <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#gradient)" fill-opacity="0.1">DeM-iON</text>
   </svg>
      </header>
<div class="container">
{% block content %}
{% endblock content %}
</div>
</body>
</html>

ecom/templates/ecom/history.html
{% load static %}
{% load pwa %}

<!doctype html>
<html lang="ja">
<head>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'ecom/css/style.css' %}" />
</head>
<body>
    <header background-color:#e6e6fa>
      <svg viewbox="0 0 100 20">
      <defs>
       <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
         <stop offset="5%" stop-color="#326384"/>
         <stop offset="95%" stop-color="#123752"/>
       </linearGradient>
       <pattern id="wave" x="0" y="0" width="120" height="20" patternUnits="userSpaceOnUse">
         <path id="wavePath" d="M-40 9 Q-30 7 -20 9 T0 9 T20 9 T40 9 T60 9 T80 9 T100 9 T120 9 V20 H-40z" mask="url(#mask)" fill="url(#gradient)">
           <animateTransform
               attributeName="transform"
               begin="0s"
               dur="1.5s"
               type="translate"
               from="0,0"
               to="40,0"
               repeatCount="indefinite" />
         </path>
       </pattern>
      </defs>
      <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#wave)"  fill-opacity="0.6">DeM-iON</text>
      <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#gradient)" fill-opacity="0.1">DeM-iON</text>
      </svg>
    </header>
  <h2 class="historyh2">購入履歴</h2>
    <table id="mytable">
        <tr>
          <th>商品名</th>
          <th>個数</th>
          <th>購入日時</th>
        </tr>
  {% for rireki in data %}

        <script>
            var json = JSON.parse("{{rireki.item}}".replace(/&#39;/g, '\"'));
            for(var i in json)
            {
                var tr="<tr>";
                var td1="<td>" + i + "</td>";
                var td2="<td>" + json[i] + "</td>";
                var td3="<td>" + "{{rireki.date}}" + "</td>";
                var td4="</tr>";
        
                $("#mytable").append(tr+td1+td2+td3+td4); 
        
            }  
        </script>
            
  {% endfor %}
    </table>
    <div class="rebtn">
        <a href="/ecom/" class="btn-circle-stitch">戻る</a>
    </div>

</body>


</html>

ecom/templates/ecom/index.html
{% load pwa %}
<!doctype html>
<html lang="ja">
<head>
    {% progressive_web_app_meta %}
</head>
<body>
    <p>index</p>
    {% for product in products %}
    <tr>
      <td><a href="{% url 'product' %}?product={{ product.product }}">{{ product.product }}</a></td><br>
      <td>{{ product.price }}円</td><br>
    </tr>
    <br>
    {% endfor %}
    <a href="{% url 'pay' %}">決済へ</p>

</body>
</html>

ecom/templates/ecom/index1.html
{% load static %}
{% load pwa %}

<!doctype html>
<html lang="ja">
<head>
    {% progressive_web_app_meta %}
    <script src="{% static 'ecom/js/pace.min.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'ecom/css/pace-theme-center-circle.min.css' %}" />
    <link rel="stylesheet" type ="text/css"
          href="{% static 'ecom/css/style.css' %}" />
    <script type="text/javascript" src="{% static 'ecom/js/jquery-3.3.1.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r75/three.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>
    <script type="text/javascript" src="{% static 'ecom/js/bas.js' %}"></script>
    <script type="text/javascript" src="{% static 'ecom/js/OrbitControls-2.js' %}"></script>
    <!--<script type="text/javascript" src="{% static 'ecom/js/hoge.js' %}"></script>-->
    <script type="text/javascript" src="{% static 'ecom/js/three.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'ecom/js/trackball_ctrl_r62.js' %}"></script>
    <script type="text/javascript" src="{% static 'ecom/js/pixel_particle.js' %}"></script>
    <link rel="shortcut icon" href="../static/ecom/img/ecom_img.ico" type="image/x-icon">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
</head>
<body>


<div class="wrapperloading">
   <!--
   <img class="heder-img" src="{% static 'ecom/img/header_img.png' %}" style="width: 100%;">-->
  <!--
  <video id="bg-video" src="../static/ecom/img/t2r29-gzu41 (1) (1).mp4" poster="../static/ecom/img/t2r29-gzu41 (1) (1).gif" autoplay loop muted playsinline></video>
  -->
<div id="player"></div>
<script>
var tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player('player', {
    height: '810',
    width: '100%',
    videoId: 'DXY3kiAonKA',
    playerVars: {
    playsinline:1,
    loop:1,
    controls:0,
    iv_load_policy:3,
    showinfo:0,
    rel:0,
    disablekb:1,
    modestbranding:1,
    wmode:'transparent'
    },
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
}


function onPlayerReady(event) {
  event.target.mute();
  event.target.playVideo();
}

function onPlayerStateChange(event) {
 if (event.data == YT.PlayerState.ENDED) {
    event.target.playVideo();
  }
}


</script>
<style>
    #player {
     position: fixed;
    width: 315%;
    height: 100%;
    z-index: -100;
    right: -104%;
    }

</style>
  <header background-color:#e6e6fa>
     <svg viewbox="0 0 100 20">
   <defs>
    <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
      <stop offset="5%" stop-color="#326384"/>
      <stop offset="95%" stop-color="#123752"/>
    </linearGradient>
    <pattern id="wave" x="0" y="0" width="120" height="20" patternUnits="userSpaceOnUse">
      <path id="wavePath" d="M-40 9 Q-30 7 -20 9 T0 9 T20 9 T40 9 T60 9 T80 9 T100 9 T120 9 V20 H-40z" mask="url(#mask)" fill="url(#gradient)">
        <animateTransform
            attributeName="transform"
            begin="0s"
            dur="1.5s"
            type="translate"
            from="0,0"
            to="40,0"
            repeatCount="indefinite" />
      </path>
    </pattern>
   </defs>
   <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#wave)"  fill-opacity="0.6">DeM-iON</text>
   <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#gradient)" fill-opacity="0.1">DeM-iON</text>
   </svg>
      </header>
   <div class="blank_top"></div>
   <div class="index-main-tables">
    {% for product in products %}
   <div class="index-table">
    <a href="{% url 'product' %}?product={{ product.product }}">
      <img src="{{ product.picture }}">
      <!-- <img src="{% static 'ecom/img/1.png' %}"> -->
      <br>
      {{ product.product }}<br>
      <span>{{ product.price }}円</span><br>
    </a>
   </div>
    {% endfor %}
   </div>
   <footer>
     <div class="footer_buttnos">
     <div class="login_pop" id="logpop">
       <h1>
          <a href="history.html"><Strong>{{request.user.username}}</Strong></a>でログイン中
       </h1>
       <h2>
         ログアウトは<a href="logout/">こちら</a>から
       </h2>
     </div>
     <ul>
       <a href="{% url 'pay' %}" class="cart_button" id="cart"><i class="fas fa-shopping-cart"></i><li>カート</li></a>
       <a href="{% url 'payf' %}" class="money_button" id="money"><i class="fas fa-money-check"></i><li>決済</li></a>
       <div onclick="wallet()">
            <div class="icon_wallet_op" id="wallet_op">
               <div class="icon_button_upper btn_up_act" id="button_upper"></div>
               <div class="icon_button_under btn_un_act" id="button_under"></div>
            </div>
       </div>
     </ul>
   </div>
 </footer>
 <script>
 var login_pop = document.getElementById('logpop');
 var wallet_op = document.getElementById('button_upper');
 var wallet_clo = document.getElementById('button_under');
 var money = document.getElementById('money');
 var cart = document.getElementById('cart');
 var count = 0;
 var count_div = 0;

 function wallet(){
   count += 1;
   count_div = count % 2;
    /*console.log(count);*/
   console.log(count_div);
if(count_div == 1){
  logpop.classList.add('log_act');
  button_upper.classList.remove('btn_up_act');
  button_under.classList.remove('btn_un_act');
  money.classList.add('active');
  money.removeAttribute("href");
  cart.classList.add('active');
  cart.removeAttribute("href");
}
else{
  logpop.classList.remove('log_act');
  button_upper.classList.add('btn_up_act');
  button_under.classList.add('btn_un_act');
  money.classList.remove('dis_no');
  cart.classList.remove('dis_no');
  money.classList.remove('active');
  cart.classList.remove('active');
  money.setAttribute("href","{% url 'payf' %}");
  cart.setAttribute("href","{% url 'pay' %}");
}
 }

 Pace.on('done', function(){

             $('.wrapperloading').fadeIn();

         });
 </script>
</div>
</body>
</html>

ecom/templates/ecom/login.html
{% load pwa %}
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    {% progressive_web_app_meta %}
</head>
<body>
    <p>login</p>
<form method="post">
    {% csrf_token %}
    {{ login }}
    <input type="submit" name="button_2" value="ログイン"><br>
</form>
</body>
</html>

ecom/templates/ecom/pay1.html
{% extends 'ecom/base.html'%}

{% block content%}
<style>
h1 {text-align:center;}
h3 {text-align:center;}
</style>

<br>
<br>
<br>
<br>
<br>
<h1><centre><Strong> 商品のご購入には<a href= "/ecom/login"><Strong>ログイン</Strong><a>が必要です</centre>
</h1>
<br>
<h3> <centre> <a href="/ecom/signup"> 登録こちらから<a></centre></h3>

{%endblock%}

ecom/templates/ecom/product.html
{% load static %}
{% load pwa %}

<!doctype html>
<html lang="ja">
<head>
    {% progressive_web_app_meta %}
    <link rel="stylesheet" type ="text/css"
          href="{% static 'ecom/css/style.css' %}" />
    <link rel="shortcut icon" href="../static/ecom/img/ecom_img.ico" type="image/x-icon">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
</head>
<body class="product-body">
    <header background-color:#e6e6fa>
     <svg viewbox="0 0 100 20">
   <defs>
    <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
      <stop offset="5%" stop-color="#326384"/>
      <stop offset="95%" stop-color="#123752"/>
    </linearGradient>
    <pattern id="wave" x="0" y="0" width="120" height="20" patternUnits="userSpaceOnUse">
      <path id="wavePath" d="M-40 9 Q-30 7 -20 9 T0 9 T20 9 T40 9 T60 9 T80 9 T100 9 T120 9 V20 H-40z" mask="url(#mask)" fill="url(#gradient)">
        <animateTransform
            attributeName="transform"
            begin="0s"
            dur="1.5s"
            type="translate"
            from="0,0"
            to="40,0"
            repeatCount="indefinite" />
      </path>
    </pattern>
   </defs>
   <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#wave)"  fill-opacity="0.6">DeM-iON</text>
   <text text-anchor="middle" x="50" y="15" font-size="18" fill="url(#gradient)" fill-opacity="0.1">DeM-iON</text>
   </svg>
      </header>
    <p class="product-img"><img src="{{ product.picture }}"></p>



<div class="product-form">
  <form name='product_form' method="POST">
    {% csrf_token %}
    <p class="product-name">{{ product.product }}</p>
    <p class="product-price">{{ product.price }}円 / 本</p>
    <div class="product-input">
    {{ form }}
    </div>
    <!-- <div class="popup-overlay" >
     <div class="popup-content" >
        <h2>商品をカートに追加しました！</h2>
        <p> 商品追加ありがとうございます。まだまだお買い物を楽しんでくださいませ！！</p>
        <button class="close">Close</button>
     </div>
    </div> -->
    <!-- <input type="submit" name="button_1" value="カートへ入れる" class="open"><br> -->
      <p><a id="submit_btn" class="modalOpen btn-square-shadow">カートへ入れる</a></p>
       <div class="modal" id="modal02">
         <div class="overLay modalClose"></div>
         <div class="inner">
         <a href="" class="modalClose">×</a>
         <h2 id="modal_text"></h2>
         <p>ほんとによろしいですか？ </p>
         <input type="submit" class="open btn-square-shadow-modal" value='いいよ'>
         <button class="modalClose btn-square-shadow">だめよ</button>
         </div>
       </div>
    </form>
        <!--
        <script type="text/javascript" src="{% static 'ecom/js/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'ecom/js/popup.js' %}"></script>
        -->
    <a href="pay.html" class="btn-square-shadow">決済へ</a>
</div>

<div class="product-contents">
    <h2>詳細</h2>
    <p class="product-text">{{ product.description }}</p>
</div>
<div class="rebtn">
  <a href="/ecom/" class="btn-circle-stitch">商品一覧</a>
</div>
<p class = "userName" id = "userName" style = "display: none"> {{ cart.person }} </p>
<p class = "price" id = "price" style = "display: none"> {{ product.price }} </p>
<script>
	let userName = $('#userName')[0].textContent.trim();
	let products = JSON.parse(localStorage.getItem(userName + "_products"));
  console.log(products);
	if (!products)
		products = {};
	$('.open').click((event) => {
		let productName = $('.product-name')[0].textContent;
		let productId = productName.trim();
    console.log(Number($('#id_number')[0].value));
		let productQuantity = Number($('#id_number')[0].value);
		let productPrice = Number($('#price')[0].textContent);
		let imageSrc = $('.product-img').find('img')[0].src;
		if (!products[productId])
			products[productId] = {name: productName, quantity: 0, price: productPrice, imgSrc: imageSrc};
		products[productId].quantity = productQuantity;
		localStorage.setItem(userName + "_products", JSON.stringify(products));
		// let price = localStorage.getItem(userName+ "_price");
		// if (price === "0" || !price)
		// 	price = 0;
		// else
	  //   price= Number(JSON.parse(price));
		// price += productQuantity * productPrice;
    // console.log(price)
		// localStorage.setItem(userName+ "_price", JSON.stringify(price));
    });

  $(function(){
    $("#submit_btn").click(function(){
      let number = document.product_form.number;
      let num = number.selectedIndex;
      if(num == 0){
        alert('本数を選択してください')
      } else{
      document.getElementById("modal_text").textContent = "{{ product.product }}を" + String(num) + "本カートへ追加します";
      $('#modal02').show();}
    });
    $(".modalClose").click(function(){
      $('#modal02').hide();
     // var parentsID = $(this).parents(".modal").attr("id");
     // if(parentsID === "modal02") {
     //   $(this).parents(".modal").children(".inner").css("animation","modalClose 0.5s forwards");
     // }
     // $(this).parents(".modal").fadeOut();
     // $(".modalOpen").removeClass("open");
     // return false;
    });
  });


</script>
</body>
</html>